# Generated by Django 4.2 on 2023-10-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('mobile', models.CharField(blank=True, max_length=64, null=True)),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')])),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('class_result', models.CharField(max_length=32)),
                ('probablistic', models.FloatField()),
                ('logtime', models.DateTimeField()),
                ('trust', models.CharField(max_length=32)),
            ],
        ),
    ]
